# Generated by Django 3.2.5 on 2021-07-22 07:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdm', models.CharField(choices=[('AGL', 'AGILE'), ('WRF', 'WATERFALL'), ('INC', 'INCREMENTAL'), ('RAD', 'RAD'), ('ITR', 'ITR'), ('SPR', 'SPIRAL')], default='INC', max_length=3)),
                ('repos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='../images')),
                ('sdm', models.CharField(choices=[('DEV', 'DEVELOPER'), ('MGR', 'MANAGER'), ('NON', 'NONE')], default='NON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('CMP', 'COMPLETED'), ('SUB', 'SUBMITTED'), ('PEN', 'PENDING'), ('DOI', 'DOING'), ('REJ', 'REJECTED')], default='PEN', max_length=3)),
                ('due', models.DateField()),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projmangtool.registereduser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projmangtool.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projmangtool.registereduser'),
        ),
    ]
