# Generated by Django 3.2.5 on 2021-07-26 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='sdm',
            new_name='role',
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='registered',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
