# Generated by Django 3.2.5 on 2021-07-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0002_auto_20210726_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='occupation',
            field=models.CharField(default='Developer', max_length=20),
        ),
    ]
