# Generated by Django 3.2.5 on 2021-08-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0003_registereduser_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='username',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
