# Generated by Django 3.2.5 on 2021-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0004_registereduser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='username',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
