# Generated by Django 3.1 on 2021-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0008_auto_20210802_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='fname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='lname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='mname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='occupation',
            field=models.TextField(default='Developer', max_length=20),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='role',
            field=models.TextField(choices=[('DEV', 'DEVELOPER'), ('MGR', 'MANAGER'), ('NON', 'NONE')], default='NON', max_length=3),
        ),
    ]
