# Generated by Django 3.1 on 2021-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0009_auto_20210803_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='mname',
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='last_name',
            field=models.TextField(max_length=20),
        ),
    ]
