# Generated by Django 3.1 on 2021-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0011_auto_20210805_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
