# Generated by Django 3.1 on 2021-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0012_auto_20210805_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='registered',
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.  Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
