# Generated by Django 3.1 on 2021-08-09 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0013_auto_20210805_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('DEV', 'DEVELOPER'), ('MGR', 'MANAGER'), ('NON', 'UNASSIGNED')], default='NON', max_length=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projs', to='projmangtool.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
