# Generated by Django 3.1 on 2021-08-09 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0014_auto_20210809_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repos',
        ),
        migrations.AlterField(
            model_name='task',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
