# Generated by Django 3.1 on 2021-08-10 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmangtool', '0016_auto_20210810_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
